# Generated by Django 5.2.3 on 2025-06-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_submission_canvas_json_submission_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(upload_to='tasks_image/'),
        ),
    ]
