# Generated by Django 5.2.3 on 2025-07-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
    ]
