# Generated by Django 5.2.3 on 2025-07-08 11:37

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_staffuser'),
        ('tasks', '0010_reviewsubmissions_submission_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('questions', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedSubmissions',
            fields=[
            ],
            options={
                'verbose_name': '📤 Submitted Dashboard',
                'verbose_name_plural': '📤 Submitted Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='reviewsubmissions',
            options={'verbose_name': '🕵️ Review pending/rejected Submissions', 'verbose_name_plural': '🕵️ Review pending/rejected Submissions'},
        ),
        migrations.AddField(
            model_name='submission',
            name='marks_per_question',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='warnings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='question_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.questionpaper'),
        ),
    ]
