# Generated by Django 5.2.3 on 2025-07-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_questionpaper_submittedsubmissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
